repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
    -   id: go-imports
    -   id: golangci-lint
    -   id: go-unit-tests